experiment_name: vjepa2_single_domain
seed: 1337
wandb:
  project: 3d-oct-foundation-model
  entity: laynzzz-university-at-buffalo
  log_artifacts: true
  ckpt_artifact_name: "${experiment_name}-ckpt"

# data
gcs_root: gs://layne-tpu-code-sync/OCTdata/OCTdata
manifest_path: ${gcs_root}/manifest.tsv
list_strategy: single_domain    # [single_domain|multi_domain]
cache_local: true
cache_dir: /tmp/oct_cache

# spatial
target_spacing: [0.05, 0.02, 0.02]  # [dz, dy, dx] mm
image_size: [64, 384, 384]          # [D, H, W]
patch_size: [4, 16, 16]
mask_ratio: 0.6

# train
global_batch_size: 32                # Reduced from 128 to handle DICOM failures
per_core_batch_size: 1              # Reduced from 2 to minimize batch impact
grad_accum_steps: 2                 # Reduced from 8 to maintain effective batch size
epochs: 120
base_lr: 1.5e-3
weight_decay: 0.05
warmup_epochs: 10
ema_base: 0.996

# logging/ckpt
ckpt_dir: gs://layne-tpu-code-sync/checkpoints/vjepa2/${experiment_name}
ckpt_every_epochs: 5
log_every_steps: 50

# loader
workers: 0  # Fixed: multiprocessing causes 'mappingproxy' serialization errors
prefetch_factor: 2
pin_memory: false