experiment_name: vjepa2_smoke_test
seed: 1337
wandb:
  project: 3d-oct-foundation-model
  entity: laynzzz-university-at-buffalo
  log_artifacts: false
  ckpt_artifact_name: "${experiment_name}-ckpt"

# data
gcs_root: gs://layne-tpu-code-sync/OCTdata/OCTdata
manifest_path: ${gcs_root}/manifest.tsv
list_strategy: single_domain    # [single_domain|multi_domain]
cache_local: true
cache_dir: /tmp/oct_cache
max_samples: 8  # Limit to 8 samples for faster smoke test

# spatial
target_spacing: [0.05, 0.02, 0.02]  # [dz, dy, dx] mm
image_size: [16, 128, 128]          # Much smaller to prevent OOM [D, H, W]
patch_size: [4, 16, 16]
mask_ratio: 0.6

# train - minimal for smoke test
global_batch_size: 4  # Reduced to prevent OOM: 4 รท (1 ร 4) = 1 grad_accum_steps
per_core_batch_size: 1
grad_accum_steps: 1
epochs: 1
max_steps: 10  # Stop after 10 steps
base_lr: 1.5e-3
weight_decay: 0.05
warmup_epochs: 0
ema_base: 0.996

# mixed precision
use_bf16: true  # Modern replacement for XLA_USE_BF16 env var

# logging/ckpt - COMPLETELY disable checkpointing for smoke test
ckpt_dir: ""  # Empty string to disable checkpointing entirely
ckpt_every_epochs: 999  # Don't save checkpoints
log_every_steps: 2

# loader
workers: 0  # Fixed: multiprocessing causes 'mappingproxy' serialization errors
prefetch_factor: null  # Must be null when workers=0
pin_memory: false